---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
  run_list:
  - recipe[rackspace_apt]

- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
  run_list:
  - recipe[rackspace_apt]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[rackspace_apt_test]
  attributes:
    rackspace_apt:
      switch:
        enable_rackspace_mirrors: true
      repos:
        apt.puppetlabs.com:
          precise: [main,dependencies]        

- name: cacher-client
  run_list:
  - recipe[minitest-handler]
  - recipe[rackspace_apt_test::cacher-client]
  attributes: {}

- name: cacher-ng
  run_list:
  - recipe[minitest-handler]
  - recipe[rackspace_apt_test::cacher-ng]
  attributes: {}

- name: cacher-ng-client
  run_list:
  - recipe[minitest-handler]
  - recipe[rackspace_apt_test::cacher-ng-client]
  attributes:
    rackspace_apt:
      config: 
        cacher_server: 
          CacheDir: 
            value: '/tmp/apt-cacher'
          Port: 
            value: '9876'
      switch:
        cacher_server:       
          cacher_interface: 'eth0'
        compiletime: true

- name: lwrps
  run_list:
  - recipe[minitest-handler]
  - recipe[rackspace_apt_test::lwrps]
  attributes: {}
